
#ifndef _COMMON_AUDIO_H_
#define _COMMON_AUDIO_H_

#define INPUT_MASTER_CLOCK_HZ   4194304.0
#define SAMPLE_FREQUENCY        48000.0

#define SAMPLE_INTERVAL_MS                      (1.0 / (SAMPLE_FREQUENCY / 1000.0))
#define MASTER_CLOCK_TICKS_PER_MS               (INPUT_MASTER_CLOCK_HZ / 1000.0)
#define MASTER_CLOCK_TICKS_PER_SAMPLE           (SAMPLE_INTERVAL_MS * MASTER_CLOCK_TICKS_PER_MS)

#endif